import { area, defineSection, image, text } from "../define";

export const journalBlog = defineSection({
  key: "journal.blog",
  module: "journal",
  title: "Trang danh sách Blog (/blog)",
  description: "Phần đầu trang và tiêu đề các khối. Bài viết quản lý ở mục Blog.",
  previewPath: "/blog",
  fields: [
    text("seoTitle", "SEO — tiêu đề trang"),
    area("seoDescription", "SEO — mô tả", { rows: 2 }),
    text("badge", "Nhãn nhỏ đầu trang"),
    text("title", "Tiêu đề", { width: "half" }),
    text("titleAccent", "Tiêu đề nhấn", { width: "half" }),
    area("intro", "Giới thiệu", { rows: 3 }),
    text("postsStatLabel", "Nhãn số bài viết", { width: "half" }),
    text("categoriesStatLabel", "Nhãn số chuyên mục", { width: "half" }),
    text("exploreLabel", "Chữ liên kết khám phá"),
    image("heroImage", "Ảnh đầu trang", { folder: "blog", width: "half" }),
    text("heroImageAlt", "Mô tả ảnh", { width: "half" }),
    text("heroCardEyebrow", "Thẻ trên ảnh — nhãn", { width: "half" }),
    text("heroCardTitle", "Thẻ trên ảnh — tiêu đề", { width: "half" }),
    text("verticalLabel", "Chữ dọc cạnh ảnh"),
    text("featuredEyebrow", "Bài nổi bật — nhãn", { width: "half" }),
    text("featuredTitle", "Bài nổi bật — tiêu đề", { width: "half" }),
    area("featuredDescription", "Bài nổi bật — mô tả", { rows: 2 }),
    text("libraryEyebrow", "Thư viện — nhãn", { width: "half" }),
    text("libraryTitle", "Thư viện — tiêu đề", { width: "half" }),
    text("allCategoryLabel", "Tên bộ lọc tất cả", { width: "half" }),
    text("readLabel", "Chữ “Đọc bài”", { width: "half" }),
    text("emptyMessage", "Thông báo khi chuyên mục trống"),
  ],
  defaults: {
    seoTitle: "Bí Kíp Làm Đẹp & Chăm Sóc Da",
    seoDescription:
      "Bài viết chuyên sâu về Melalogy Energy Shot, bí kíp chăm sóc da và trang điểm phù hợp với người Việt.",
    badge: "Melalogy Journal · Số 08/2026",
    title: "Đọc chậm.",
    titleAccent: "Đẹp lâu.",
    intro:
      "Kiến thức chăm sóc da được chắt lọc, những góc nhìn làm đẹp có chiều sâu và câu chuyện thương hiệu dành riêng cho người Việt.",
    postsStatLabel: "bài tuyển chọn",
    categoriesStatLabel: "chuyên mục",
    exploreLabel: "Khám phá ngay",
    heroImage: "/assets/melalogy-blog-hero-2026.png",
    heroImageAlt: "Phụ nữ Việt Nam chăm sóc da dưới ánh sáng buổi sáng",
    heroCardEyebrow: "Chủ đề tháng này",
    heroCardTitle: "Hiểu làn da của bạn",
    verticalLabel: "Beauty · Science · Culture",
    featuredEyebrow: "Bài đọc nổi bật",
    featuredTitle: "Chọn bởi ban biên tập",
    featuredDescription:
      "Góc nhìn mới nhất về thương hiệu, hoạt chất và những thói quen giúp làn da khỏe đẹp bền vững.",
    libraryEyebrow: "Thư viện kiến thức",
    libraryTitle: "Đọc theo nhịp của bạn",
    allCategoryLabel: "Tất Cả",
    readLabel: "Đọc bài",
    emptyMessage: "Chuyên mục này đang được biên tập. Mời bạn quay lại trong ít phút nữa.",
  },
});

export const journalMagazine = defineSection({
  key: "journal.magazine",
  module: "journal",
  title: "Trang danh sách Tạp chí (/magazine)",
  description: "Phần đầu trang, tiêu đề các khối và khối đăng ký nhận bản tin.",
  previewPath: "/magazine",
  fields: [
    text("seoTitle", "SEO — tiêu đề trang"),
    area("seoDescription", "SEO — mô tả", { rows: 2 }),
    text("badge", "Nhãn nhỏ đầu trang"),
    text("title", "Tiêu đề", { width: "half" }),
    text("titleAccent", "Tiêu đề nhấn", { width: "half" }),
    area("intro", "Giới thiệu", { rows: 2 }),
    text("tags", "Các chủ đề (phân cách bằng dấu phẩy)"),
    text("coverLabel", "Nhãn bài trang bìa", { width: "half" }),
    text("studioLabel", "Nhãn trên ảnh bìa", { width: "half" }),
    text("indexEyebrow", "Danh sách — nhãn", { width: "half" }),
    text("indexTitle", "Danh sách — tiêu đề", { width: "half" }),
    area("indexDescription", "Danh sách — mô tả", { rows: 2 }),
    text("newsletterLabel", "Bản tin — nhãn"),
    text("newsletterTitle", "Bản tin — tiêu đề"),
    area("newsletterDescription", "Bản tin — mô tả", { rows: 2 }),
    text("newsletterPlaceholder", "Bản tin — gợi ý ô email", { width: "half" }),
    text("newsletterButton", "Bản tin — chữ trên nút", { width: "half" }),
    text("newsletterSuccessTitle", "Bản tin — thông báo thành công"),
    text("newsletterSuccessDescription", "Bản tin — mô tả thông báo"),
  ],
  defaults: {
    seoTitle: "Tạp Chí: Thương Hiệu, Khoa Học & Vẻ Đẹp Việt",
    seoDescription:
      "Câu chuyện chuyên sâu về thương hiệu Melalogy, khoa học melanin, Energy Shot và văn hóa làm đẹp dành cho người Việt.",
    badge: "Số 08 · Tháng 8/2026",
    title: "Tạp chí của",
    titleAccent: "làn da.",
    intro: "Khoa học, văn hóa và những góc nhìn đẹp hơn về cách người Việt chăm sóc làn da mỗi ngày.",
    tags: "Khoa học, Văn hóa, Chân dung",
    coverLabel: "Câu chuyện trang bìa",
    studioLabel: "Melalogy Studio · 2026",
    indexEyebrow: "Từ ban biên tập",
    indexTitle: "Tám lát cắt mới",
    indexDescription:
      "Những câu chuyện ngắn để hiểu làn da, thiết kế và vẻ đẹp Việt theo một cách gần gũi hơn.",
    newsletterLabel: "Melalogy Notes · Mỗi tháng",
    newsletterTitle: "Một lá thư đẹp, không làm đầy hộp thư.",
    newsletterDescription:
      "Bài đọc mới, kiến thức chăm da và những câu chuyện hậu trường được tuyển chọn vừa đủ.",
    newsletterPlaceholder: "email@cuaban.vn",
    newsletterButton: "Nhận số mới",
    newsletterSuccessTitle: "Đã đăng ký Melalogy Notes",
    newsletterSuccessDescription: "Bản tuyển chọn mới sẽ được gửi đến hộp thư của bạn.",
  },
});
