-- Customer accounts: addresses, orders, order_items
-- Adds self-service profile updates (name only — role/is_active protected by trigger),
-- a saved address book, and an order history backed by RLS so customers only ever
-- see their own data. Staff (editor/admin/super_admin) can see every order for the
-- admin order-management screen that will ship in a follow-up.

create type public.order_status as enum (
  'pending',
  'confirmed',
  'processing',
  'shipped',
  'completed',
  'cancelled'
);

create type public.payment_method as enum (
  'cod',
  'bank_transfer'
);

create type public.payment_status as enum (
  'unpaid',
  'awaiting_confirmation',
  'paid',
  'refunded'
);

-- Prevent a customer from granting themselves admin rights through the new
-- "update own profile" policy below: role/is_active can only change when the
-- acting user already has admin rights (checked via public.is_admin()).
create or replace function public.protect_profile_privileges()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (new.role is distinct from old.role or new.is_active is distinct from old.is_active)
     and not public.is_admin(array['super_admin']::public.user_role[]) then
    new.role := old.role;
    new.is_active := old.is_active;
  end if;
  return new;
end;
$$;

create trigger profiles_protect_privileges
before update on public.profiles
for each row execute function public.protect_profile_privileges();

create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using (id = (select auth.uid()))
with check (id = (select auth.uid()));

create table public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  full_name text not null,
  phone text not null,
  address text not null,
  ward text not null default '',
  district text not null default '',
  city text not null default '',
  note text,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint addresses_full_name_not_blank check (length(trim(full_name)) > 0),
  constraint addresses_phone_not_blank check (length(trim(phone)) > 0),
  constraint addresses_address_not_blank check (length(trim(address)) > 0)
);

create index addresses_user_idx on public.addresses(user_id);

create unique index addresses_one_default_per_user
  on public.addresses(user_id)
  where is_default;

create trigger addresses_set_updated_at
before update on public.addresses
for each row execute function public.set_updated_at();

alter table public.addresses enable row level security;

create policy "Users can view their own addresses"
on public.addresses for select
to authenticated
using (user_id = (select auth.uid()));

create policy "Users can manage their own addresses"
on public.addresses for all
to authenticated
using (user_id = (select auth.uid()))
with check (user_id = (select auth.uid()));

create table public.orders (
  id bigint generated by default as identity primary key,
  order_code text not null unique,
  user_id uuid references public.profiles(id) on delete set null,
  status public.order_status not null default 'pending',
  payment_method public.payment_method not null,
  payment_status public.payment_status not null default 'unpaid',
  subtotal integer not null default 0,
  shipping_fee integer not null default 0,
  total integer not null default 0,
  shipping_full_name text not null,
  shipping_phone text not null,
  shipping_address text not null,
  shipping_ward text not null default '',
  shipping_district text not null default '',
  shipping_city text not null default '',
  shipping_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_subtotal_non_negative check (subtotal >= 0),
  constraint orders_shipping_fee_non_negative check (shipping_fee >= 0),
  constraint orders_total_non_negative check (total >= 0)
);

create index orders_user_idx on public.orders(user_id);
create index orders_created_at_idx on public.orders(created_at desc);

create trigger orders_set_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

create table public.order_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_name text not null,
  product_image text,
  unit_price integer not null,
  quantity integer not null,
  line_total integer not null,
  created_at timestamptz not null default now(),
  constraint order_items_quantity_positive check (quantity > 0),
  constraint order_items_unit_price_non_negative check (unit_price >= 0),
  constraint order_items_line_total_non_negative check (line_total >= 0)
);

create index order_items_order_idx on public.order_items(order_id);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

create policy "Users can view their own orders"
on public.orders for select
to authenticated
using (user_id = (select auth.uid()));

create policy "Users can create their own orders"
on public.orders for insert
to authenticated
with check (user_id = (select auth.uid()));

create policy "Staff can view all orders"
on public.orders for select
to authenticated
using (public.is_admin());

create policy "Staff can manage all orders"
on public.orders for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Users can view items of their own orders"
on public.order_items for select
to authenticated
using (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = (select auth.uid())
  )
);

create policy "Users can create items for their own orders"
on public.order_items for insert
to authenticated
with check (
  exists (
    select 1 from public.orders
    where orders.id = order_items.order_id
      and orders.user_id = (select auth.uid())
  )
);

create policy "Staff can view all order items"
on public.order_items for select
to authenticated
using (public.is_admin());
