create extension if not exists pgcrypto;

create type public.user_role as enum (
  'customer',
  'editor',
  'admin',
  'super_admin'
);

create type public.publication_status as enum (
  'draft',
  'published',
  'archived'
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null default '',
  full_name text,
  role public.user_role not null default 'customer',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.categories (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.categories(id) on delete set null,
  name text not null,
  slug text not null unique,
  description text,
  image_url text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint categories_name_not_blank check (length(trim(name)) > 0),
  constraint categories_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table public.products (
  id bigint generated by default as identity primary key,
  category_id bigint references public.categories(id) on delete set null,
  name text not null,
  slug text not null unique,
  sku text unique,
  subtitle text,
  short_description text,
  description text,
  ingredients text,
  usage text,
  price integer not null default 0,
  compare_at_price integer,
  status public.publication_status not null default 'draft',
  featured boolean not null default false,
  sort_order integer not null default 0,
  seo_title text,
  seo_description text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint products_name_not_blank check (length(trim(name)) > 0),
  constraint products_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint products_price_non_negative check (price >= 0),
  constraint products_compare_at_price_non_negative check (compare_at_price is null or compare_at_price >= 0)
);

create table public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id bigint not null references public.products(id) on delete cascade,
  storage_path text,
  image_url text not null,
  alt_text text,
  sort_order integer not null default 0,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  constraint product_images_url_not_blank check (length(trim(image_url)) > 0)
);

create unique index product_images_one_primary_per_product
  on public.product_images(product_id)
  where is_primary;

create index product_images_product_sort_idx
  on public.product_images(product_id, sort_order);

create table public.banners (
  id bigint generated by default as identity primary key,
  name text not null,
  placement text not null default 'home_hero',
  eyebrow text,
  title text not null,
  highlighted_text text,
  subtitle text,
  desktop_image_url text not null,
  mobile_image_url text,
  button_label text,
  button_url text,
  secondary_button_label text,
  secondary_button_url text,
  sort_order integer not null default 0,
  status public.publication_status not null default 'draft',
  starts_at timestamptz,
  ends_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint banners_name_not_blank check (length(trim(name)) > 0),
  constraint banners_title_not_blank check (length(trim(title)) > 0),
  constraint banners_dates_valid check (ends_at is null or starts_at is null or ends_at > starts_at)
);

create index banners_public_listing_idx
  on public.banners(placement, status, sort_order);

create table public.homepage_sections (
  id bigint generated by default as identity primary key,
  section_key text not null unique,
  eyebrow text,
  title text not null,
  highlighted_text text,
  subtitle text,
  body text,
  image_url text,
  cta_label text,
  cta_url text,
  content jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  status public.publication_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint homepage_sections_key_format check (section_key ~ '^[a-z0-9]+(?:_[a-z0-9]+)*$'),
  constraint homepage_sections_title_not_blank check (length(trim(title)) > 0)
);

create table public.site_settings (
  key text primary key,
  value jsonb not null default 'null'::jsonb,
  is_public boolean not null default false,
  updated_at timestamptz not null default now(),
  constraint site_settings_key_format check (key ~ '^[a-z0-9]+(?:_[a-z0-9]+)*$')
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

create trigger categories_set_updated_at
before update on public.categories
for each row execute function public.set_updated_at();

create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

create trigger banners_set_updated_at
before update on public.banners
for each row execute function public.set_updated_at();

create trigger homepage_sections_set_updated_at
before update on public.homepage_sections
for each row execute function public.set_updated_at();

create trigger site_settings_set_updated_at
before update on public.site_settings
for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (
    new.id,
    coalesce(new.email, ''),
    nullif(new.raw_user_meta_data ->> 'full_name', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

insert into public.profiles (id, email, full_name)
select
  id,
  coalesce(email, ''),
  nullif(raw_user_meta_data ->> 'full_name', '')
from auth.users
on conflict (id) do nothing;

create or replace function public.is_admin(
  accepted_roles public.user_role[] default array['editor', 'admin', 'super_admin']::public.user_role[]
)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and is_active = true
      and role = any(accepted_roles)
  );
$$;

revoke all on function public.is_admin(public.user_role[]) from public;
grant execute on function public.is_admin(public.user_role[]) to authenticated;

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.banners enable row level security;
alter table public.homepage_sections enable row level security;
alter table public.site_settings enable row level security;

create policy "Users can view their own profile"
on public.profiles for select
to authenticated
using (id = (select auth.uid()));

create policy "Super admins can manage profiles"
on public.profiles for all
to authenticated
using (public.is_admin(array['super_admin']::public.user_role[]))
with check (public.is_admin(array['super_admin']::public.user_role[]));

create policy "Public can view active categories"
on public.categories for select
to anon, authenticated
using (is_active = true);

create policy "Admins can manage categories"
on public.categories for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Public can view published products"
on public.products for select
to anon, authenticated
using (status = 'published');

create policy "Admins can manage products"
on public.products for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Public can view images for published products"
on public.product_images for select
to anon, authenticated
using (
  exists (
    select 1 from public.products
    where products.id = product_images.product_id
      and products.status = 'published'
  )
);

create policy "Admins can manage product images"
on public.product_images for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Public can view active banners"
on public.banners for select
to anon, authenticated
using (
  status = 'published'
  and (starts_at is null or starts_at <= now())
  and (ends_at is null or ends_at > now())
);

create policy "Admins can manage banners"
on public.banners for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Public can view published homepage sections"
on public.homepage_sections for select
to anon, authenticated
using (status = 'published');

create policy "Admins can manage homepage sections"
on public.homepage_sections for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Public can view public settings"
on public.site_settings for select
to anon, authenticated
using (is_public = true);

create policy "Admins can manage site settings"
on public.site_settings for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'melalogy-media',
  'melalogy-media',
  true,
  5242880,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Admins can list Melalogy media"
on storage.objects for select
to authenticated
using (bucket_id = 'melalogy-media' and public.is_admin());

create policy "Admins can upload Melalogy media"
on storage.objects for insert
to authenticated
with check (bucket_id = 'melalogy-media' and public.is_admin());

create policy "Admins can update Melalogy media"
on storage.objects for update
to authenticated
using (bucket_id = 'melalogy-media' and public.is_admin())
with check (bucket_id = 'melalogy-media' and public.is_admin());

create policy "Admins can delete Melalogy media"
on storage.objects for delete
to authenticated
using (bucket_id = 'melalogy-media' and public.is_admin());
