create type public.content_channel as enum (
  'blog',
  'magazine'
);

create table public.articles (
  id bigint generated by default as identity primary key,
  channel public.content_channel not null,
  slug text not null,
  title text not null,
  seo_title text,
  meta_description text,
  keywords text[] not null default '{}',
  subtitle text,
  excerpt text not null default '',
  author text not null default 'Đội ngũ Melalogy',
  author_role text,
  date_label text,
  published_at timestamptz,
  category text not null,
  image_url text not null,
  image_alt text not null default '',
  reading_time text not null default '5 phút đọc',
  content_html text not null default '',
  status public.publication_status not null default 'draft',
  featured boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint articles_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint articles_title_not_blank check (length(trim(title)) > 0),
  constraint articles_category_not_blank check (length(trim(category)) > 0),
  constraint articles_image_url_not_blank check (length(trim(image_url)) > 0),
  constraint articles_channel_slug_unique unique (channel, slug)
);

create index articles_public_listing_idx
  on public.articles(channel, status, featured desc, sort_order, published_at desc);

create table public.content_pages (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  seo_title text,
  seo_description text,
  content jsonb not null default '{}'::jsonb,
  status public.publication_status not null default 'draft',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint content_pages_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  constraint content_pages_title_not_blank check (length(trim(title)) > 0),
  constraint content_pages_content_object check (jsonb_typeof(content) = 'object')
);

create trigger articles_set_updated_at
before update on public.articles
for each row execute function public.set_updated_at();

create trigger content_pages_set_updated_at
before update on public.content_pages
for each row execute function public.set_updated_at();

alter table public.articles enable row level security;
alter table public.content_pages enable row level security;

create policy "Public can view published articles"
on public.articles for select
to anon, authenticated
using (
  status = 'published'
  and (published_at is null or published_at <= now())
);

create policy "Admins can manage articles"
on public.articles for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Public can view published content pages"
on public.content_pages for select
to anon, authenticated
using (status = 'published');

create policy "Admins can manage content pages"
on public.content_pages for all
to authenticated
using (public.is_admin())
with check (public.is_admin());
